### ISSUE TITLE
UGen is not recognized on Windows 10

### ISSUE THREAD

**Issue by gantz-giraffe** [brianlheim/simplegain#1]
I managed to get this built via cookiecutter and cmake on Windows 10, copied the `\simplegain\build\install\SimpleGain\SimpleGain` folder into my extensions directory (`AppData\Local\SuperCollider\Extensions,`), but upon trying to use it SC produces the error 

> 
>  exception in GraphDef_Recv: UGen 'SimpleGain' not installed.
> *** ERROR: SynthDef temp__0 not found
> FAILURE IN SERVER /s_new SynthDef not found

**Comment by mossheim** [comment]
please open this on the cookiecutter repo, this repo is just for demonstration purposes

**Comment by mossheim** [comment]
https://github.com/supercollider/cookiecutter-supercollider-plugin

**Comment by gantz-giraffe** [comment]
I was going to originally, but it doesn't appear that the issues feature is enabled in that repo.

**Comment by mossheim** [comment]
sorry! it is available now.
